title: WebX Specification
description: The modern WebX Specification.

url: "https://spec.webxplus.org"
baseurl: "/"
permalink: pretty

theme: just-the-docs
color_scheme: dark
heading_anchors: true

callouts:
  note:
    title: Note
    color: blue
  deprecated:
    title: Deprecated
    color: red

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      has_toc: false

plugins:
  - jekyll-relative-links
  - jekyll-sitemap

relative_links:
  enabled: true
  collections: true